# NumPy

In [1]:
import sys
import numpy as np

print(sys.version)
print('NumPy: {}'.format(np.__version__))

3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
NumPy: 1.20.1


In [2]:
%%html
<style>
table {float:left}
</style>

## 変形(次元の変換)

In [3]:
# データの用意
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 1次元配列時の`shape`関数の出力
np.shape(a)

(10,)

### 次元の追加
1次元の配列を、2次元に変換する

In [5]:
# 変形したい配列内容をタプルで指定
b = a.reshape((2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

[numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html?highlight=reshape#numpy.reshape)

### 1次元配列に戻す

In [6]:
# ravelメソッドは参照を返す
b.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[numpy.ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html?highlight=ravel#numpy.ravel)

In [7]:
# flattenメソッドはコピーを返す
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[numpy.flatten](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

## データ型の確認・変換

In [8]:
# データ型の確認
a = np.arange(1, 6)
a.dtype

dtype('int64')

In [9]:
# データ型の変換
a = np.arange(1, 6)
a.astype(np.float16)

array([1., 2., 3., 4., 5.], dtype=float16)

Pythonデータ型とNumPy`dtype`メソッド表示のデータ型との対応表

| Python3(64bit) | NumPy |
|:---:|:---:|
| int | int64 |
| float | float64 |
| str | unicode |


## 浅いコピー(shallow copy)と深いコピー(deep copy)

Pythonにおけるmutableな複合データ型の`shallow copy`と`deep copy`について

> Python において代入文はオブジェクトをコピーしません。代入はターゲットとオブジェクトの間に束縛を作ります。ミュータブルなコレクションまたはミュータブルなアイテムを含むコレクションについては、元のオブジェクトを変更せずにコピーを変更できるように、コピーが必要になることが時々あります。  
>  
> 浅い(shallow)コピーと深い(deep)コピーの違いが関係するのは、複合オブジェクト(リストやクラスインスタンスのような他のオブジェクトを含むオブジェクト)だけです。  
> ・浅いコピー(shallow copy)は新たな複合オブジェクトを作成し、その後 (可能な限り) 元のオブジェクト中に見つかったオブジェクトに対する「参照」を挿入します。  
> ・深いコピー(deep copy)は新たな複合オブジェクトを作成し、その後元のオブジェクト中に見つかったオブジェクトの「コピー」を挿入します。  

[Python: copy --- 浅いコピーおよび深いコピー操作](https://docs.python.org/ja/3/library/copy.html)

In [10]:
# shallow copyの例
a = np.array([0, 0])
a1 = a
a1[0] = 1
print('a:  {}'.format(a))
print('a1: {}'.format(a1))

# deep copyの例
b = np.array([0, 0])
b1 = b.copy()
b1[0] = 1
print('b:  {}'.format(b))
print('b1: {}'.format(b1))

a:  [1 0]
a1: [1 0]
b:  [0 0]
b1: [1 0]


In [11]:
# ravelメソッドはshallow copy
c = np.array([[0, 0], [0, 0]])
c1 = c.ravel()
c1[0] = 1
print('c  ravel: {}'.format(c))
print('c1 ravel: {}'.format(c1))

# flattenメソッドはdeep copy
d = np.array([[0, 0], [0, 0]])
d1 = d.flatten()
d1[0] = 1
print('d  ravel: {}'.format(d))
print('d1 ravel: {}'.format(d1))

c  ravel: [[1 0]
 [0 0]]
c1 ravel: [1 0 0 0]
d  ravel: [[0 0]
 [0 0]]
d1 ravel: [1 0 0 0]


In [12]:
# NumPyのndarrayの場合、スライスでの代入はshallow copyとなるので注意
np_array1 = np.array([0, 0])
np_array2 = np_array1[:]
np_array2[0] = 1
print('np_array1: {}'.format(np_array1))
print('np_array2: {}'.format(np_array2))

# Pythonではdeep copyである
py_list1 = [0, 0]
py_list2 = py_list1[:]
py_list2[0] = 1
print('py_list1:  {}'.format(py_list1))
print('py_list2:  {}'.format(py_list2))


np_array1: [1 0]
np_array2: [1 0]
py_list1:  [0, 0]
py_list2:  [1, 0]


## 乱数の生成

[Random sampling](https://numpy.org/doc/stable/reference/random/index.html)

### 0から1までを範囲とする一様乱数の生成

In [13]:
np.random.seed(123)
# 生成する乱数の次元と要素をタプルで渡す
np.random.random((2, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

[numpy.random.random](https://docs.python.org/dev/library/random.html#random.random)

In [14]:
np.random.seed(123)
# 生成する乱数の次元と要素を引数で渡す
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

[numpy.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=random%20rand)

### 整数値の一様乱数の生成

In [15]:
np.random.seed(123)
# 乱数の範囲と、次元と要素を指定
np.random.randint(1, 10, size=(2, 3))

array([[3, 3, 7],
       [2, 4, 7]])

[numpy.random.randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint)

### 少数値の一様乱数の生成

In [16]:
np.random.seed(123)
# 乱数の範囲と、次元と要素を指定
np.random.uniform(0.0, 10.0, size=(2, 3))

array([[6.96469186, 2.86139335, 2.26851454],
       [5.51314769, 7.1946897 , 4.2310646 ]])

[numpy.random.uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html?highlight=random%20uniform#numpy.random.uniform)

### 標準正規分布(平均0、標準偏差1の正規分布)に従った乱数の生成

In [17]:
np.random.seed(123)
# 標準正規分府(平均0、標準偏差1の分布)で生成
np.random.randn(2, 3)

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

[numpy.random.randn](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html?highlight=random%20randn#numpy.random.randn)

In [18]:
np.random.seed(123)
# 平均0、標準偏差5の分布で生成
np.random.normal(loc=0, scale=5, size=(2, 3))

array([[-5.42815302,  4.98672723,  1.41489249],
       [-7.53147357, -2.89300126,  8.25718269]])

[numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html?highlight=random%20normal#numpy.random.normal)

## 同じ要素(`0.0`や`1.0`)の数列を作成

In [19]:
# 1x3の「0.0」の配列を作成
np.zeros(3)

array([0., 0., 0.])

In [20]:
# 2x2の「0.0」の配列を作成
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

[numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [21]:
# 1x3の「1.0」の配列を作成
np.ones(3)

array([1., 1., 1.])

In [22]:
# 2x2の「1.0」の配列を作成
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

[numpy.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

## 単位行列の作成

- 単位行列とは、以下の条件を満たす行列のこと
  - 正方行列
  - 左上から右下までの対角線となる成分が、すべて1となる
  - 残りの成分が、すべて0となる

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

[numpy.eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye)

## 指定値で埋める

2次元3要素の配列を、`3.14`という値で作成する

In [24]:
np.full((2, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

[numpy.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html?highlight=full#numpy.full)

欠損値の穴埋めに`numpy.nan`という値が利用される

- numpy.nan
  - 特殊な定数
  - `Not a Number`のこと
  - float型に分類
  - NumPyの以下の事情により用意されている
    - ndaarayには同じデータ型のみが格納できるため
    - Noneや空文字がある場合に計算不可能となってしまうため


In [25]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

## データを均等値で割る

In [26]:
# 0から100までに値を分割する　以下例では、5つの要素(4分割)に分けている
np.linspace(0, 100, num=5)

array([  0.,  25.,  50.,  75., 100.])

[numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace)

## 連結

2つのndarrayを、1つのndarrayに連結する

In [27]:
# 連結用データの準備
np.random.seed(123)
A = np.random.randint(0, 10, size=(2,2))
print('A: \n{}'.format(A))
B = np.random.randint(0, 10, size=(2,2))
print('B: \n{}'.format(B))

A: 
[[2 2]
 [6 1]]
B: 
[[3 9]
 [6 1]]


### 列方向の追加(要素の追加)

In [28]:
np.concatenate([A, B], axis=1)

array([[2, 2, 3, 9],
       [6, 1, 6, 1]])

[numpy.concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

In [29]:
np.hstack([A, B])

array([[2, 2, 3, 9],
       [6, 1, 6, 1]])

[numpy.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack)

horizontal ... 水平線

### 行方向の追加(次元の追加)

In [30]:
np.concatenate([A, B], axis=0)

array([[2, 2],
       [6, 1],
       [3, 9],
       [6, 1]])

In [31]:
np.vstack([A, B])

array([[2, 2],
       [6, 1],
       [3, 9],
       [6, 1]])

[numpy.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)

vertical ... 垂直

## 分割

1つのndarrayを、2つのndarrayに分ける

### 列方向に分割(要素で分割)

[NumPy.hsplit](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html)

In [32]:
# データの用意
a = np.arange(16).reshape(4, 4)

# 第2引数で3を指定したため、要素数3と1の配列に分割される
np.hsplit(a, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

### 行方向に分割(次元で分割)

[NumPy.vsplit](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html)

In [33]:
# データの用意
a = np.arange(16).reshape(4, 4)

# 第2引数で3を指定したため、次元数3と1の配列に分割される
np.vsplit(a, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## 転置
配列の次元(行)と要素(列)を入れ替える

In [34]:
# データの用意
np.random.seed(123)
m = np.random.randint(0, 10, size=[5, 2])
m

array([[2, 2],
       [6, 1],
       [3, 9],
       [6, 1],
       [0, 1]])

In [35]:
m.transpose()

array([[2, 6, 3, 6, 0],
       [2, 1, 9, 1, 1]])

[numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html?highlight=ndarray%20transpose#numpy.ndarray.transpose)

In [36]:
# エイリアスがある
m.T

array([[2, 6, 3, 6, 0],
       [2, 1, 9, 1, 1]])

## 次元追加

In [37]:
a = np.array([1, 2, 3])

# 行方向にスライシング(2次元配列にする)
print('ndim: {}'.format(a.ndim))
b = a[np.newaxis, :]
print(b)
print('ndim: {}'.format(b.ndim))

ndim: 1
[[1 2 3]]
ndim: 2


In [38]:
a = np.array([1, 2, 3])

# 列方向にスライシング
print('ndim: {}'.format(a.ndim))
b = a[:, np.newaxis]
print(b)
print('ndim: {}'.format(b.ndim))

ndim: 1
[[1]
 [2]
 [3]]
ndim: 2


- `reshape`と`newaxis`との違い
  - `reshape`は要素数を指定する必要がある
  - `newaxis`は要素数を指定する必要がない

## グリッドデータの生成
- x座標、y座標の配列から、それらを組み合わせてできる全ての点を生成
- 等高線やヒートマップに利用

In [39]:
# データの用意
m = np.arange(0, 4)
print('m: {}'.format(m))
n = np.arange(4, 7)
print('n: {}'.format(n))

m: [0 1 2 3]
n: [4 5 6]


In [40]:
xx, yy = np.meshgrid(m, n)
print('xx: \n{}'.format(xx))
print('yy: \n{}'.format(yy))

xx: 
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
yy: 
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


[numpy.meshgrid](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html)

> Return coordinate matrices from coordinate vectors.  
> 座標ベクトルから座標行列を返す.


## ユニバーサルファンクション

- NumPyの配列(ndarray)の全要素に対して、要素ごとに演算処理を行う関数
- map関数みたいなイメージ


### 絶対値を算出
[numpy.absolute](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html?highlight=abs)

In [41]:
a = np.arange(-3, 3).reshape(2, 3)
np.abs(a)

array([[3, 2, 1],
       [0, 1, 2]])

### sin(正弦)の計算
[numpy.sin](https://numpy.org/doc/stable/reference/generated/numpy.sin.html?highlight=sin#numpy.sin)

In [42]:
a = np.linspace(-1, 1, 10)
np.sin(a)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

### cos(余弦)の計算
[numpy.cos](https://numpy.org/doc/stable/reference/generated/numpy.cos.html?highlight=cos)

In [43]:
a = np.linspace(-1, 1, 10)
np.cos(a)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

### 対数関数 $f(x)=log_2x$ の計算

[numpy.log2](https://numpy.org/doc/stable/reference/generated/numpy.log2.html)

- 底が3や5の対数関数はユニバーサルファンクションで用意されてないぽい？

In [44]:
a = np.array([8, 16, 20])
np.log2(a)

array([3.        , 4.        , 4.32192809])

### 常用対数 $f(x)=log_{10}x$ の計算

[numpy.log10](https://numpy.org/doc/stable/reference/generated/numpy.log10.html#numpy.log10)

In [45]:
a = np.array([10, 100, 150])
np.log10(a)

array([1.        , 2.        , 2.17609126])

### 自然対数 $f(x)=log_ex$ の計算

[numpy.log](https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log)

In [46]:
a = np.array([0, 1, 2])
np.log(a)

<ipython-input-46-41c45fc026f8>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

xが0である自然対数(x)は定義されていないため`-inf`となる

### 底をネイピア数とする指数関数 $f(x)=e^x$ の計算

[numpy.exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html?highlight=exp#numpy.exp)

In [47]:
a = np.array([0, 1, 2])
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

## ブロードキャスト

ndarray同士の二項演算(四則演算など)において、ndarrayの形状(shape)が同じとなるように、自動的に変換して処理してくれる機能

In [48]:
# 配列にスカラーの加算
a = np.array([1, 3, 5])
a + 10

array([11, 13, 15])

In [49]:
# 次元数の異なる配列同士の加算
a = np.array([1, 3, 5])
b = np.array([[1, 3, 5], [2, 4, 6]])
a + b

array([[ 2,  6, 10],
       [ 3,  7, 11]])

aの配列が2次元の配列となり(既存の1行目がコピーされて)、加算処理がされている

In [50]:
# 次元数も要素数も異なる配列同士の加算
a = np.array([1, 3, 5])
a1 = a[:, np.newaxis]
a + a1

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10]])

「1x3」の配列(a)と「3x1」の配列(a1)の加算であるが、それぞれ配列を「3x3」の配列に拡張して処理されている

In [51]:
# 次元数も要素数も異なる配列同士の乗算
a = np.array([1, 3, 5])
a1 = a[:, np.newaxis]
a * a1

array([[ 1,  3,  5],
       [ 3,  9, 15],
       [ 5, 15, 25]])

In [52]:
## 累乗
a = np.array([1, 3, 5])
a ** 3

array([  1,  27, 125])

In [53]:
# 割り算(0があるとinfになる)
a = np.array([0, 2, 4])
b = np.array([4, 2, 0])
a / b

<ipython-input-53-a0180767f102>:4: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([ 0.,  1., inf])

In [54]:
# 1e-6(10の-6乗)という微小の数値を足した後割り算をすることで、近似値を出力させinfを避ける
a = np.array([0, 2, 4])
b = np.array([4, 2, 0])
a / (b+1e-6)

array([0.000000e+00, 9.999995e-01, 4.000000e+06])

## ドット積

- ベクトル演算の一種で、2つの同じ長さの数列から1つの数値(スカラー)を返す演算
- 幾何的定義では、ユークリッド空間において標準的に定義される内積のこと

[numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

> ・If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).  
> ・If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.  
> ・If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.  
> ・If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.  
> ・If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b.


### If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

In [55]:
# aとbがともに1次元の配列: ベクトルの内積
a = np.array([1, 2])
b = np.array([1, 3])
np.dot(a, b)

7

### If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [56]:
# aとbの両方が2次元配列: 行列の乗算, matmul or 「a @ b」
a = np.array([[1, 2], [1, 2]])
b = np.array([[1, 3], [1, 3]])
np.dot(a, b)

array([[3, 9],
       [3, 9]])

In [57]:
# 「@」でエイリアスになっている
a @ b

array([[3, 9],
       [3, 9]])

In [58]:
# 「matmul」での同じ結果となる
np.matmul(a, b)

array([[3, 9],
       [3, 9]])

[NumPy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html?highlight=matmul)

> Matrix product of two arrays.

In [59]:
# 正方行列と単位行列の掛け算は、順番を入れ替えても同じになる
c = np.random.randint(1, 10, size=(3, 3))
d = np.eye(3)
print(np.dot(c, d))
print('---')
print(np.dot(d, c))

[[1. 1. 4.]
 [5. 1. 1.]
 [5. 2. 8.]]
---
[[1. 1. 4.]
 [5. 1. 1.]
 [5. 2. 8.]]


### If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

In [60]:
# aまたはbのどちらかが0-D（スカラー）の場合: numpy.multiply(a, b)または 「a * b」
a = np.array([1, 2])
np.dot(a, 3)

array([3, 6])

In [61]:
np.multiply(a, 3)

array([3, 6])

In [62]:
a * 3

array([3, 6])

### If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

In [63]:
# aをN次元配列、bを1次元配列の場合: aとbの最後の軸上の和積
a = np.array([[1, 2], [1, 3]])
b = np.array([1, 4])
np.dot(a, b)

array([ 9, 13])

### If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b.

In [64]:
# aをN次元配列、bをM次元配列(M>=2)の場合: aの最後の軸とbの最後から2番目の軸の和積
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.array([[1, 1], [2, 2]])
np.dot(1, b)

array([[1, 1],
       [2, 2]])

## 判定・論理値

### 配列とスカラーの比較

In [65]:
a = np.array([[0, 1, 2], [0, 1, 2]])
a > 1

array([[False, False,  True],
       [False, False,  True]])

In [66]:
# Trueの数をカウントする(Falseは0として扱われるので、以下でTrueの数を拾ってこれる)
np.count_nonzero(a > 1)

2

In [67]:
# sumでも可能(Trueを1として扱うため)
np.sum(a > 1)

2

In [68]:
# Trueが含まれるかどうか
np.any(a > 1)

True

In [69]:
# すべてがTrueかどうか
np.all(a > 1)

False

### 判定・論理値の真偽値を利用して、条件に合致する要素のみ出力する

In [70]:
a = np.array([[0, 1, 2], [0, 1, 2]])
a[a > 1]

array([2, 2])

### 配列同士の比較

In [71]:
# 同じ形状の配列を比較
a = np.array([1, 2])
b = np.array([1, 3])
a == b

array([ True, False])

In [72]:
# 異なる形状の配列を比較(ブロードキャストのルールに従って比較)
a = np.array([1, 2])
b = np.array([[1, 2], [1, 3]])
a == b

array([[ True,  True],
       [ True, False]])

In [73]:
# 配列の比較結果を用いたビット演算
a = np.array([1, 2])
b = np.array([[1, 2], [5, 3]])
c = np.array([1, 6])
(a == b) | (a == c)

array([[ True,  True],
       [ True, False]])

In [74]:
# 条件の合う要素(Trueとなる要素)のみを配列から取得
a = np.array([1, 2])
b = np.array([[1, 2], [5, 3]])
c = np.array([1, 6])
b[(a == b) | (a == c)]

array([1, 2, 5])

### allcloseメソッド
[numpy.allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)

In [75]:
# 配列同士が同じ要素で構成されているか確認
a = np.array([1, 5])
b = np.array([1, 10])
np.allclose(a, b)

False

In [76]:
# atolパラメーターで、誤差の範囲を指定して比較する
np.allclose(a, b, atol=10)

True